use std::f64::consts::PI;

pub const SECONDS_PER_YEAR: f64 = 365.0 * 24.0 * 3600.0;
pub const KM_PER_EARTH_RADIUS: f64 = 6371.0;
pub const METERS_PER_EARTH_RADIUS: f64 = KM_PER_EARTH_RADIUS * 1000.0;

pub const METERS_PER_SECOND_PER_EARTH_RADII_PER_YEAR: f64 =
    METERS_PER_EARTH_RADIUS / SECONDS_PER_YEAR;

pub const EARTH_MASSES_PER_SUN_MASS: f64 = 333000.0;
pub const EARTH_RADII_PER_AU: f64 = 23_455.0;
pub const G: f64 = 4.0 * PI * PI * EARTH_RADII_PER_AU * EARTH_RADII_PER_AU * EARTH_RADII_PER_AU
    / EARTH_MASSES_PER_SUN_MASS;
pub const SUN_MU: f64 = G * EARTH_MASSES_PER_SUN_MASS;

pub const LITTLE_G: f64 = 9.80665; // [m/s]
