use std::collections::VecDeque;

/// Queue for storing messages generated by GUI components
pub struct MsgQueue<Msg> {
    queue: VecDeque<Msg>,
}

impl<Msg> MsgQueue<Msg> {
    /// Create a new MsgQueue
    pub fn new() -> Self {
        Self {
            queue: VecDeque::new(),
        }
    }

    /// Adds a new element to the end of the queue
    pub fn push(&mut self, msg: Msg) {
        self.queue.push_back(msg);
    }

    /// Removes and returns the first msg in the queue, or None
    pub fn pop(&mut self) -> Option<Msg> {
        self.queue.pop_front()
    }
}

impl<Msg> IntoIterator for MsgQueue<Msg> {
    type Item = Msg;
    type IntoIter = std::collections::vec_deque::IntoIter<Msg>;
    fn into_iter(self) -> Self::IntoIter {
        self.queue.into_iter()
    }
}
