[[parts]]
id = "station_core"
name = "Station Core"
desc = "Core of the station."
dry_mass_kg = 676767676767.0
energy_kwh = 100000.0


[[parts]]
id = "metal"
name = "Metal"
desc = "Boring hunk of metal."
dry_mass_kg = 900.0
inputs = {} # TODO: Ilmetite ore
resources = {water = 10.0}
energy_kwh = 350.0 # way too little but just go with it
