[[parts]]
id = 'vernier'
name = 'Vernier Pack'
desc = 'Cold gas thrusters. Barely a stage'
dry_mass_kg = 12.0
[parts.fuel]
max_fuel_mass_kg = 8.0
isp = 65.0
thrust_kn = 0.05


[[parts]]
id = 'monoprop_kick'
name = 'Monopropellant Kick Stage'
desc = 'Simple and adorable'
dry_mass_kg = 28.0
[parts.fuel]
max_fuel_mass_kg = 140.0
isp = 228.0
thrust_kn = 0.8


[[parts]]
id = 'hypergolic_transfer'
name = 'Hypergolic Transfer Stage'
desc = 'Dont look at this one funny'
dry_mass_kg = 190.0
[parts.fuel]
max_fuel_mass_kg = 1_100.0
isp = 320.0
thrust_kn = 4.5


[[parts]]
id = 'hypergolic_descent'
name = 'Hypergolic Descent Stage'
desc = 'Dissolve anything in your way'
dry_mass_kg = 900.0
[parts.fuel]
max_fuel_mass_kg = 6_000.0
isp = 311.0
thrust_kn = 45.0
