//! This module is responsible for defining the gameplay scene.

use std::{collections::HashMap, f64::consts::PI, sync::Arc};

use apricot::{
    app::{App, Scene},
    bvh::BVH,
    camera::{Camera, ProjectionKind},
    high_precision::{self, WorldPosition},
    opengl::create_program,
    rectangle::Rectangle,
    render_core::{LinePathComponent, ModelComponent},
    shadow_map::DirectionalLightSource,
};
use hecs::{Entity, World};
use nalgebra_glm::{vec3, DVec3};
use sdl2::keyboard::Scancode;

use crate::{
    components::{
        body::{spawn_body, Body, Category, Orbit, Parent, SceneObject},
        button::{Button, Event, EventQueue},
    },
    generation::solar_system_gen::{self},
};

/// Object file data, used for meshes
pub const QUAD_XY_DATA: &[u8] = include_bytes!("../../res/quad-xy.obj");
pub const ICO_DATA: &[u8] = include_bytes!("../../res/ico-sphere.obj");
pub const UV_DATA: &[u8] = include_bytes!("../../res/uv-sphere.obj");

/// Struct that contains info about the game state
pub struct Gameplay {
    /// The world where all the entities live
    world: World,
    /// The camera used for rendering 3d models
    camera_3d: high_precision::Camera,
    /// The sun's light source
    directional_light: DirectionalLightSource,
    /// A bounding-volume hierarchy, a container that stores models and allows for efficient lookup for fast rendering
    bvh: BVH<Entity>,

    /// Which planetary body is currently selected
    selection: usize,
    /// The radius of the currently selected planetary body, for limiting zoom
    selected_body_radius: f64,
    /// The position of the selected planetary body, used for swoosh animation
    selected_pos: DVec3,
    /// The prev selected position, used for swoosh animation
    prev_selected_pos: DVec3,
    /// Animation key frame counter
    transition: f64,

    /// Up-down view angle
    phi: f64,
    /// Side-side view angle
    theta: f64,
    /// How far the camera swivels around the currently selected body
    distance: f64,

    /// Used for enter key latch
    prev_enter_state: bool,
    /// How many planets there are
    bodies: Vec<Entity>,

    /// Queue of events generated by the GUI this current tick
    event_queue: Arc<EventQueue>,

    turn: usize,
    turn_transition_time: f64,
}

impl Scene for Gameplay {
    /// Update the scene every tick
    fn update(&mut self, app: &App) {
        // Update all the buttons
        for (_entity, button) in self.world.query_mut::<&mut Button>() {
            button.update(app);
        }

        // Loop through the events in the event queue and respond to them
        while let Some(event) = self.event_queue.pop() {
            match event {
                // Handle all the buttons
                Event::ButtonClicked(id) => match id {
                    "next-turn" => {
                        if (app.seconds as f64 - self.turn_transition_time) >= 1.0 {
                            self.turn += 1;
                            self.turn_transition_time = app.seconds as f64;
                            println!("doing the next turn!")
                        }
                    }
                    _ => panic!("unknown button id: {:?}", id),
                },
            }
        }

        self.control(app);
        self.orbit_system(app);
        self.select_system();
        self.line_path_system(app);
        self.camera_update(app);
    }

    /// Render the scene to the screen when time allows
    fn render(&mut self, app: &App) {
        self.directional_light.light_dir = -self.camera_3d.inner.position().normalize();
        app.renderer.set_camera(self.camera_3d.inner);
        app.renderer.directional_light_system(
            &mut self.directional_light,
            &mut self.world,
            &self.bvh,
        );
        app.renderer.render_3d_models_system(
            &mut self.world,
            &self.directional_light,
            &self.bvh,
            Some(&self.camera_3d),
            false,
        );

        let font = app.renderer.get_font_id_from_name("font").unwrap();
        app.renderer.set_font(font);
        for (entity, scene_obj) in self.world.query::<&SceneObject>().iter() {
            if entity == self.bodies[self.selection] {
                app.renderer
                    .draw_text(nalgebra_glm::vec2(10.0, 10.0), &scene_obj.name);
            }
        }

        for (_entity, button) in self.world.query_mut::<&mut Button>() {
            button.render(app);
        }

        app.renderer.draw_text(
            nalgebra_glm::vec2(
                app.window_size.x as f32 - 90.0,
                app.window_size.y as f32 - 20.0,
            ),
            format!("turn: {}", self.turn).to_string().as_str(),
        );

        app.renderer
            .render_3d_line_paths(&self.world, Some(&self.camera_3d));
    }
}

impl Gameplay {
    /// Constructs a new Gameplay struct with everything setup
    /// TODO: Most of this stuff will need to be moved to the init scene. Remind me to make an issue for this!
    pub fn new(app: &App) -> Self {
        let mut world = World::new();

        // Add programs to the renderer
        app.renderer.add_program(
            create_program(
                include_str!("../shaders/3d.vert"),
                include_str!("../shaders/3d.frag"),
            )
            .unwrap(),
            Some("3d"),
        );
        app.renderer.add_program(
            create_program(
                include_str!("../shaders/2d.vert"),
                include_str!("../shaders/2d.frag"),
            )
            .unwrap(),
            Some("2d"),
        );
        app.renderer.add_program(
            create_program(
                include_str!("../shaders/shadow.vert"),
                include_str!("../shaders/shadow.frag"),
            )
            .unwrap(),
            Some("shadow"),
        );
        app.renderer.add_program(
            create_program(
                include_str!("../shaders/2d.vert"),
                include_str!("../shaders/solid-color.frag"),
            )
            .unwrap(),
            Some("2d-solid"),
        );
        app.renderer.add_program(
            create_program(
                include_str!("../shaders/3d.vert"),
                include_str!("../shaders/solid-color.frag"),
            )
            .unwrap(),
            Some("3d-solid"),
        );
        app.renderer.add_program(
            create_program(
                include_str!("../shaders/line.vert"),
                include_str!("../shaders/solid-color.frag"),
            )
            .unwrap(),
            Some("line"),
        );

        // Setup the mesh manager
        app.renderer
            .add_mesh_from_obj(QUAD_XY_DATA, Some("quad-xy"));
        app.renderer.add_mesh_from_obj(UV_DATA, Some("uv"));
        app.renderer.add_mesh_from_obj(ICO_DATA, Some("ico"));

        // Setup the texture manager
        app.renderer
            .add_texture_from_png("res/sun.png", Some("sun"));
        app.renderer
            .add_texture_from_png("res/venus.png", Some("venus"));
        app.renderer
            .add_texture_from_png("res/earth.png", Some("earth"));
        app.renderer
            .add_texture_from_png("res/moon.png", Some("moon"));
        app.renderer
            .add_texture_from_png("res/jupiter.png", Some("jupiter"));
        app.renderer
            .add_texture_from_png("res/europa.png", Some("europa"));
        app.renderer
            .add_texture_from_png("res/uranus.png", Some("uranus"));
        app.renderer
            .add_texture_from_png("res/next-turn.png", Some("next-turn"));
        app.renderer
            .add_texture_from_png("res/next-turn-hover.png", Some("next-turn-hover"));

        // Setup the font manager
        app.renderer
            .add_font("res/Consolas.ttf", "font", 16, sdl2::ttf::FontStyle::NORMAL);

        let mut bvh = BVH::<Entity>::new();

        let sun_entity = spawn_body(
            Body {
                category: Category::Star,
                body_radius: 110.0,
                rotation_period_hours: 0.0,
                rotation: 0.0,
                atmos_pressure: 1000000.0,
                temperature: 5778.0,
                core_mass_fraction: 0.0,
                magnetic_field: true,
                density: 1.0,
            },
            Orbit {
                semi_major_axis: 0.0,
                eccentricity: 0.0,
                inclination: 0.0,
                longitude_of_ascending_node: 0.0,
                argument_of_periapsis: 0.0,
                mean_anomaly_at_epoch: 0.0,
                period: 0.0,
            },
            SceneObject {
                bvh_node_id: None,
                name: String::from("Sun"),
            },
            None,
            &mut world,
            &app.renderer,
            &mut bvh,
        );

        let mut bodies = vec![sun_entity];

        let planets = solar_system_gen::generate();
        for system in planets {
            let planet_entity = spawn_body(
                system.planet.0,
                system.planet.1,
                SceneObject {
                    bvh_node_id: None,
                    name: String::from("planet name"),
                },
                Some(Parent { id: sun_entity }),
                &mut world,
                &app.renderer,
                &mut bvh,
            );
            bodies.push(planet_entity);

            for moon in system.moons {
                let moon_entity = spawn_body(
                    moon.0,
                    moon.1,
                    SceneObject {
                        bvh_node_id: None,
                        name: String::from("moon name"),
                    },
                    Some(Parent { id: planet_entity }),
                    &mut world,
                    &app.renderer,
                    &mut bvh,
                );
                bodies.push(moon_entity);
            }
        }

        let event_queue = Arc::new(EventQueue::new());

        world.spawn((Button::new(
            "next-turn",
            Rectangle::new(
                app.window_size.x as f32 - 100.0,
                app.window_size.y as f32 - 120.0,
                90.0,
                90.0,
            ),
            app.renderer.get_texture_id_from_name("next-turn").unwrap(),
            app.renderer
                .get_texture_id_from_name("next-turn-hover")
                .unwrap(),
            event_queue.clone(),
        ),));

        Self {
            world,
            camera_3d: high_precision::Camera {
                world_pos: vec3(1.0, 1.0, 1.0),
                inner: Camera::new(
                    vec3(1.0, 0.0, 1.0),
                    vec3(0.0, 0.0, 0.0),
                    vec3(0.0, 0.0, 1.0),
                    ProjectionKind::Perspective {
                        fov: 0.65,
                        far: 10000000.0,
                    },
                ),
            },
            bvh,
            directional_light: DirectionalLightSource::new(
                Camera::new(
                    vec3(0.0, 0.0, 0.0),
                    vec3(0.0, 10.0, 0.0),
                    vec3(0.0, 0.0, 1.0),
                    ProjectionKind::Orthographic {
                        // These do not matter for now, they're reset later
                        left: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        top: 0.0,
                        near: 0.0,
                        far: 0.0,
                    },
                ),
                vec3(-1.0, 0.0, 0.0),
                1024,
            ),

            selection: 2,
            selected_pos: vec3(0.0, 0.0, 0.0),
            prev_selected_pos: vec3(0.0, 0.0, 0.0),
            transition: 1.0,
            selected_body_radius: 0.0,
            phi: 2.5,
            theta: -PI / 4.0,
            distance: 20.0,
            prev_enter_state: false,
            bodies,

            event_queue: event_queue.clone(),

            turn: 0,
            turn_transition_time: 0.001,
        }
    }

    /// Changes various game state based on user mouse and keyboard input
    fn control(&mut self, app: &App) {
        let curr_enter_state = app.keys[Scancode::Return as usize];
        if curr_enter_state && !self.prev_enter_state {
            self.selection += 1;
            self.prev_selected_pos = self.selected_pos;
            self.transition = app.seconds as f64;
            if self.selection >= self.bodies.len() {
                self.selection = 0;
            }
        }
        self.prev_enter_state = curr_enter_state;

        let control_speed = 0.005;
        let zoom_control_speed = 0.15 * (self.distance - self.selected_body_radius);
        if app.mouse_left_down {
            self.phi -= control_speed * (app.mouse_vel.x as f64);
            self.theta = (self.theta - control_speed * (app.mouse_vel.y as f64))
                .max(control_speed - PI / 2.0)
                .min(PI / 2.0 - control_speed);
        }

        self.distance = (self.distance - zoom_control_speed * (app.mouse_wheel as f64))
            .max(self.selected_body_radius * 4.0)
            .min(self.selected_body_radius * 4000000.0 + 234.0);
    }

    /// Updates planets based on their on-rails orbits around their parent bodies
    fn orbit_system(&mut self, app: &App) {
        // Build parent -> children map
        let mut children: HashMap<Entity, Vec<Entity>> = HashMap::new();

        for (entity, (parent, _model)) in self.world.query::<(&Parent, &ModelComponent)>().iter() {
            children.entry(parent.id).or_default().push(entity);
        }

        // Collect all entities with WorldPosition
        let mut has_parent = HashMap::new();
        for (entity, parent) in self.world.query::<&Parent>().iter() {
            has_parent.insert(entity, parent.id);
        }

        // Find roots (entities without parent)
        let mut roots = Vec::new();
        for (entity, _) in self.world.query::<&WorldPosition>().iter() {
            if !has_parent.contains_key(&entity) {
                roots.push(entity);
            }
        }

        const TURN_TIME: f64 = 10.0;
        let t = 1.0 / 12.0
            * (self.turn as f64
                + cubic_ease_in_out(
                    ((app.seconds as f64 - self.turn_transition_time) / TURN_TIME).min(1.0),
                ));

        // Kick off from roots
        for root in roots {
            let root_pos = vec3(0.0, 0.0, 0.0);
            self.propagate(&children, root, root_pos, t, app);
        }
    }

    fn select_system(&mut self) {
        for (entity, (world_pos, planet)) in
            self.world.query_mut::<(&mut WorldPosition, &mut Body)>()
        {
            if entity == self.bodies[self.selection] {
                self.selected_pos = world_pos.pos;
                self.selected_body_radius = planet.body_radius;
            }
        }
    }

    fn propagate(
        &mut self,
        children: &HashMap<Entity, Vec<Entity>>,
        entity: Entity,
        parent_pos: DVec3,
        t: f64,
        app: &App,
    ) {
        // Borrow components
        let mut world_pos = self.world.get::<&mut WorldPosition>(entity).unwrap();
        let mut model = self.world.get::<&mut ModelComponent>(entity).unwrap();
        let scene_obj = self.world.get::<&SceneObject>(entity).unwrap();

        // Compute local offset if Orbit exists
        let local_offset = if let Ok(orbit) = self.world.get::<&Orbit>(entity) {
            let theta = 2.0 * PI * (t + orbit.mean_anomaly_at_epoch) / (orbit.period + 0.0001);
            vec3(
                theta.cos() * orbit.semi_major_axis,
                theta.sin() * orbit.semi_major_axis,
                0.0,
            )
        } else {
            vec3(0.0, 0.0, 0.0)
        };

        let new_world = parent_pos + local_offset;
        let vel = new_world - world_pos.pos;
        world_pos.pos = new_world;
        model.set_position(nalgebra_glm::convert(new_world - self.camera_3d.world_pos));
        self.bvh.move_obj(
            scene_obj.bvh_node_id.unwrap(),
            &app.renderer.get_model_aabb(&model),
            &nalgebra_glm::convert(vel),
        );

        drop(world_pos); // release borrow before recusion
        drop(model); // release borrow before recusion
        drop(scene_obj); // release borrow before recusion

        // Recurse into children
        if let Some(kids) = children.get(&entity) {
            for &child in kids {
                self.propagate(children, child, new_world, t, app);
            }
        }
    }

    fn line_path_system(&mut self, _app: &App) {
        // Extract out the world positions
        let mut pos_map = HashMap::new();
        for (entity, world_pos) in self.world.query::<&WorldPosition>().iter() {
            pos_map.insert(entity, world_pos.pos);
        }

        // Set the origins of the line paths wrt the parent world positions
        for (entity, (line, world_pos, parent)) in
            self.world
                .query_mut::<(&mut LinePathComponent, &mut WorldPosition, &Parent)>()
        {
            let parent_pos = pos_map.get(&parent.id).unwrap();

            line.color.w = if entity == self.bodies[self.selection] {
                0.8
            } else {
                0.2
            };

            world_pos.pos = *parent_pos;
        }
    }

    /// Updates the camera position and lookat based on mouse panning and body selection
    fn camera_update(&mut self, app: &App) {
        let rot_matrix = nalgebra_glm::rotate_y(
            &nalgebra_glm::rotate_z(&nalgebra_glm::one(), self.phi),
            self.theta,
        );
        let transition = cubic_ease_in_out((app.seconds as f64 - self.transition).min(1.0));
        let offset = (1.0 - transition) * self.prev_selected_pos + transition * self.selected_pos;
        self.camera_3d.world_pos =
            (rot_matrix * nalgebra_glm::vec4(self.distance, 0., 0., 0.)).xyz() + offset;
        self.camera_3d.sync(offset);
    }
}

/// Cubic easing out function - for animation
fn cubic_ease_in_out(t: f64) -> f64 {
    if t < 0.5 {
        4.0 * t * t * t
    } else {
        1.0 - (-2.0 * t + 2.0).powf(3.0) / 2.0
    }
}
